### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by kachun333** [kachun333/KMPk-1617-Grad-Mag#79]
the default branch has changed from `master` to `main`

also added a `dev` branch, all development-related PR should be targeted to the `dev` branch.

documentations or `.github` related PR can optionally merge to the `main` branch directly

### Reference:
- [React Router Contributing Guide](https://github.com/remix-run/react-router/blob/main/docs/guides/contributing.md) is a good example to follow

**Comment by kachun333** [comment]
@aswin2108 are you interested to help out?

**Comment by aswin2108** [comment]
I'll complete it!
